"""
Script para insertar palabras comunes en español a la base de datos
IMPORTANTE: Las palabras NO deben llevar acentos
"""
import pymysql
import os
from dotenv import load_dotenv

# Cargar variables de entorno
load_dotenv()

# Lista de palabras comunes en español SIN acentos
palabras = [
    # Palabras comunes A-B
    "ABAJO", "ABIERTO", "ABRAZO", "ABRIL", "ABUELA", "ABUELO", "ACABAR", "ACEITE", "ACEPTAR", "ACERO",
    "ACTIVO", "ACTOR", "ACTUAL", "ACTUAR", "ACUERDO", "ADELANTE", "ADEMAS", "ADENTRO", "ADIOS", "ADMIRAR",
    "ADOPTAR", "ADORAR", "ADULTO", "AEREO", "AFECTO", "AFUERA", "AGENDA", "AGENTE", "AGOSTO", "AGREGAR",
    "AGUA", "AGUILA", "AGUJA", "AHORA", "AHORRAR", "AIRE", "AJUSTAR", "ALARMA", "ALCALDE", "ALCANZAR",
    "ALEGRE", "ALEGRIA", "ALEJAR", "ALGO", "ALGUIEN", "ALGUNO", "ALMA", "ALMACEN", "ALMORZAR", "ALMUERZO",
    "ALREDEDOR", "ALTAR", "ALTO", "ALTURA", "ALUMNO", "ALZAR", "AMABLE", "AMANECER", "AMANTE", "AMAR",
    "AMARGO", "AMARILLO", "AMBOS", "AMENAZA", "AMENAZAR", "AMERICA", "AMIGO", "AMISTAD", "AMOR", "AMPLIO",
    "ANCHO", "ANCIANO", "ANDAR", "ANGEL", "ANGULO", "ANGUSTIA", "ANILLO", "ANIMA", "ANIMAL", "ANIMAR",
    "ANIMO", "ANOCHE", "ANOTAR", "ANSIA", "ANTE", "ANTERIOR", "ANTES", "ANTIGUO", "ANUAL", "ANUNCIAR",
    "ANUNCIO", "ANADIR", "ANO", "APAGAR", "APARATO", "APARECER", "APARTAMENTO", "APARTAR", "APARTE", "APENAS",
    "APETITO", "APLASTAR", "APLAUDIR", "APLAUSO", "APLICAR", "APODO", "APOSTAR", "APOYAR", "APOYO", "APRECIAR",
    "APRECIO", "APRENDER", "APRESURAR", "APRETAR", "APROBAR", "APROVECHAR", "APROXIMAR", "APUNTAR", "APURAR", "AQUEL",
    "AQUELLO", "AQUI", "ARANAR", "ARANA", "ARBOL", "ARBUSTO", "ARCO", "ARDER", "ARDIENTE", "ARDOR",
    "ARENA", "ARENOSO", "ARGENTINO", "ARGUMENTO", "ARIDO", "ARMA", "ARMADA", "ARMAR", "ARMARIO", "ARMONIA",
    "AROMA", "ARQUITECTO", "ARRANCAR", "ARRASTRAR", "ARREGLAR", "ARREGLO", "ARREPENTIR", "ARRIBA", "ARRIESGAR", "ARRIMAR",
    "ARRODILLAR", "ARROJAR", "ARROYO", "ARROZ", "ARRUGA", "ARRUGAR", "ARRUINAR", "ARTE", "ARTERIA", "ARTICULO",
    "ARTISTA", "ARTISTICO", "ASADO", "ASALTAR", "ASALTO", "ASAMBLEA", "ASAR", "ASCENDER", "ASCENSO", "ASCO",
    "ASEGURAR", "ASEMEJAR", "ASENTIR", "ASEO", "ASESINAR", "ASESINATO", "ASESINO", "ASIENTO", "ASIGNAR", "ASILO",
    "ASIMISMO", "ASISTENCIA", "ASISTIR", "ASNO", "ASOCIAR", "ASOMAR", "ASOMBRAR", "ASOMBRO", "ASPECTO", "ASPERO",
    "ASPIRAR", "ASQUEROSO", "ASTRO", "ASTUCIA", "ASTUTO", "ASUMIR", "ASUNTO", "ASUSTAR", "ATACAR", "ATAQUE",
    
    # Palabras comunes B-C
    "BAILAR", "BAILE", "BAJAR", "BAJO", "BALANZA", "BALCON", "BALLENA", "BALON", "BANCO", "BANDA",
    "BANDERA", "BANAR", "BANO", "BARATO", "BARBA", "BARCO", "BARRA", "BARRER", "BARRIO", "BARRO",
    "BASE", "BASTAR", "BASURA", "BATALLA", "BATERIA", "BATIR", "BAUL", "BAUTIZAR", "BEBER", "BEBIDA",
    "BELLO", "BELLEZA", "BENDECIR", "BENEFICIO", "BESAR", "BESO", "BESTIA", "BIBLIOTECA", "BICICLETA", "BIEN",
    "BIENESTAR", "BILLETE", "BLANCO", "BLANDO", "BLOQUE", "BLUSA", "BOCA", "BOCADO", "BODA", "BODEGA",
    "BOLA", "BOLETO", "BOLSA", "BOLSILLO", "BOMBA", "BONDAD", "BONITO", "BORDE", "BORRAR", "BOSQUE",
    "BOTA", "BOTAR", "BOTE", "BOTELLA", "BOTON", "BRAZO", "BREVE", "BRILLANTE", "BRILLAR", "BRILLO",
    "BRINCAR", "BRINDAR", "BRISA", "BROMA", "BRONCE", "BROTAR", "BRUJA", "BRUTO", "BUENO", "BUFANDA",
    "BURLA", "BURLAR", "BURRO", "BUSCA", "BUSCAR", "CABALLO", "CABANA", "CABELLO", "CABER", "CABEZA",
    "CABLE", "CABO", "CABRA", "CACAO", "CADA", "CADAVER", "CADENA", "CAER", "CAFE", "CAIDA",
    "CAJA", "CAJON", "CALABAZA", "CALCULAR", "CALDERA", "CALDO", "CALENDARIO", "CALENTAR", "CALIDAD", "CALIENTE",
    "CALIFICAR", "CALMA", "CALMAR", "CALOR", "CALVO", "CALZADO", "CALLE", "CAMA", "CAMARA", "CAMARERO",
    "CAMBIAR", "CAMBIO", "CAMELLO", "CAMINAR", "CAMINO", "CAMION", "CAMISA", "CAMPANA", "CAMPEON", "CAMPESINO",
    "CAMPO", "CANAL", "CANARIO", "CANASTA", "CANCELAR", "CANCION", "CANDADO", "CANDIDATO", "CANELA", "CANGURO",
    "CANSADO", "CANSAR", "CANTAR", "CANTIDAD", "CANTO", "CANA", "CANON", "CAOS", "CAPA", "CAPACIDAD",
    "CAPAZ", "CAPITAL", "CAPITAN", "CAPITULO", "CAPRICHO", "CAPTAR", "CAPTURA", "CAPTURAR", "CARA", "CARACTER",
    "CARBON", "CARCEL", "CARDENAL", "CARGAR", "CARGO", "CARICIA", "CARIDAD", "CARINO", "CARNE", "CARO",
    "CARPETA", "CARRERA", "CARRETA", "CARRETERA", "CARRO", "CARTA", "CARTEL", "CARTERA", "CARTERO", "CARTON",
    "CASA", "CASAR", "CASCADA", "CASCO", "CASERO", "CASI", "CASINO", "CASO", "CASTA", "CASTANO",
    "CASTELLANO", "CASTIGAR", "CASTIGO", "CASTILLO", "CASUAL", "CASUALIDAD", "CATEDRAL", "CATEGORIA", "CATOLICO", "CATORCE",
    
    # Palabras comunes D-E
    "DAMA", "DANZA", "DANAR", "DANO", "DATO", "DEBER", "DEBIL", "DEBILIDAD", "DECADA", "DECENTE",
    "DECIDIR", "DECIR", "DECISION", "DECLARAR", "DECORAR", "DECRETO", "DEDICAR", "DEDO", "DEFENDER", "DEFENSA",
    "DEFENSOR", "DEFINIR", "DEJAR", "DELANTE", "DELGADO", "DELICADO", "DELICIA", "DELITO", "DEMANDA", "DEMAS",
    "DEMASIADO", "DEMOCRACIA", "DEMONIO", "DEMORA", "DEMORAR", "DEMOSTRAR", "DENSO", "DENTAL", "DENTRO", "DENUNCIA",
    "DENUNCIAR", "DEPARTAMENTO", "DEPENDER", "DEPORTE", "DEPOSITAR", "DEPOSITO", "DERECHA", "DERECHO", "DERIVAR", "DERRAMAR",
    "DERRIBAR", "DERROTA", "DERROTAR", "DESAFIO", "DESAPARECER", "DESARROLLAR", "DESARROLLO", "DESASTRE", "DESAYUNAR", "DESAYUNO",
    "DESCANSAR", "DESCANSO", "DESCENDER", "DESCENSO", "DESCRIBIR", "DESCUBRIR", "DESCUENTO", "DESCUIDAR", "DESDE", "DESEAR",
    "DESECHAR", "DESEO", "DESIERTO", "DESIGNAR", "DESIGUAL", "DESLIZAR", "DESNUDO", "DESOBEDECER", "DESORDEN", "DESPACHO",
    "DESPACIO", "DESPEDIR", "DESPEGAR", "DESPERTAR", "DESPIERTO", "DESPLAZAR", "DESPRECIAR", "DESPRECIO", "DESPUES", "DESTACAR",
    "DESTINO", "DESTROZAR", "DESTRUIR", "DETALLE", "DETENER", "DETERMINAR", "DETESTAR", "DETRAS", "DEUDA", "DEUDOR",
    "DEVOLVER", "DEVORAR", "DIA", "DIABLO", "DIALOGO", "DIAMANTE", "DIARIO", "DIBUJAR", "DIBUJO", "DICCIONARIO",
    "DICIEMBRE", "DICTADOR", "DICTADURA", "DICTAR", "DIENTE", "DIETA", "DIEZ", "DIFERENCIA", "DIFERENTE", "DIFICIL",
    "DIFICULTAD", "DIFUNDIR", "DIFUNTO", "DIGESTION", "DIGNIDAD", "DIGNO", "DILIGENCIA", "DILUIR", "DIMENSION", "DIMINUTO",
    "DINERO", "DIOS", "DIPLOMA", "DIPUTADO", "DIRECCION", "DIRECTO", "DIRECTOR", "DIRIGIR", "DISCIPLINA", "DISCIPULO",
    "DISCO", "DISCORDIA", "DISCRETO", "DISCULPA", "DISCULPAR", "DISCURSO", "DISCUTIR", "DISENAR", "DISENO", "DISFRAZ",
    "DISFRAZAR", "DISFRUTAR", "DISGUSTAR", "DISGUSTO", "DISIMULAR", "DISMINUIR", "DISOLVER", "DISPARAR", "DISPARO", "DISPENSAR",
    "DISPERSAR", "DISPONER", "DISPOSICION", "DISPUESTO", "DISPUTA", "DISPUTAR", "DISTANCIA", "DISTANTE", "DISTINGUIR", "DISTINTO",
    "DISTRACCION", "DISTRAER", "DISTRIBUIR", "DISTRITO", "DISTURBAR", "DISTURBIO", "DISUADIR", "DIURNO", "DIVAGAR", "DIVAN",
    "DIVERSIDAD", "DIVERSO", "DIVERSION", "DIVERTIR", "DIVIDIR", "DIVINO", "DIVISION", "DIVORCIO", "DIVULGAR", "DOBLAR",
    "DOBLE", "DOCE", "DOCENA", "DOCIL", "DOCTOR", "DOCTRINA", "DOCUMENTO", "DOLAR", "DOLER", "DOLOR",
    
    # Palabras comunes E-F
    "EDAD", "EDIFICIO", "EDITAR", "EDUCAR", "EFECTO", "EFECTUAR", "EFICAZ", "EGOISMO", "EJECUTAR", "EJEMPLO",
    "EJERCER", "EJERCICIO", "EJERCITO", "ELABORAR", "ELECCION", "ELECTRICIDAD", "ELECTRICO", "ELEGANTE", "ELEGIR", "ELEMENTO",
    "ELEVAR", "ELIMINAR", "ELOGIO", "EMBAJADA", "EMBAJADOR", "EMBARCAR", "EMBARGO", "EMERGENCIA", "EMIGRAR", "EMITIR",
    "EMOCION", "EMOCIONAR", "EMPACAR", "EMPATAR", "EMPATE", "EMPEZAR", "EMPLEADO", "EMPLEAR", "EMPLEO", "EMPRESA",
    "EMPUJAR", "ENAMORAR", "ENCABEZAR", "ENCADENAR", "ENCAJAR", "ENCANTAR", "ENCANTO", "ENCARGAR", "ENCARGO", "ENCENDER",
    "ENCERRAR", "ENCIMA", "ENCONTRAR", "ENCUENTRO", "ENEMIGO", "ENERGIA", "ENERO", "ENFADAR", "ENFADO", "ENFERMEDAD",
    "ENFERMERA", "ENFERMO", "ENFOCAR", "ENFOQUE", "ENFRENTE", "ENFRENTAR", "ENFRIAR", "ENGANO", "ENGANAR", "ENGORDAR",
    "ENIGMA", "ENORME", "ENRIQUECER", "ENSALADA", "ENSAYAR", "ENSAYO", "ENSENAR", "ENSUCIAR", "ENTENDER", "ENTERAR",
    "ENTERO", "ENTERRAR", "ENTONCES", "ENTRADA", "ENTRANTE", "ENTRAR", "ENTRE", "ENTREGAR", "ENTRETENER", "ENTREVISTA",
    "ENTRISTECER", "ENTUSIASMO", "ENVIAR", "ENVIDIA", "ENVIDIAR", "ENVOLVER", "EPOCA", "EQUILIBRIO", "EQUIPAJE", "EQUIPO",
    "EQUIVOCACION", "EQUIVOCAR", "ERGUIR", "ERIGIR", "ERIZO", "ERMITA", "ERUDITO", "ESCALA", "ESCALAR", "ESCALERA",
    "ESCALON", "ESCAMA", "ESCANDALO", "ESCAPAR", "ESCAPE", "ESCARABAJO", "ESCARCHA", "ESCARLATA", "ESCASO", "ESCENA",
    "ESCLAVO", "ESCOBA", "ESCOGER", "ESCOLAR", "ESCOLTA", "ESCONDER", "ESCOPETA", "ESCRIBIR", "ESCRITO", "ESCRITOR",
    "ESCRITORIO", "ESCRITURA", "ESCRUPULO", "ESCUCHAR", "ESCUDO", "ESCUELA", "ESCULTOR", "ESCULTURA", "ESCUPIR", "ESCURRIR",
    "ESENCIA", "ESENCIAL", "ESFERA", "ESFUERZO", "ESGRIMA", "ESLABON", "ESMALTE", "ESMERALDA", "ESMERO", "ESPACIO",
    "ESPACIOSO", "ESPADA", "ESPALDA", "ESPANTAR", "ESPANTO", "ESPANTOSO", "ESPANA", "ESPANOL", "ESPARCIR", "ESPARTO",
    "ESPECIAL", "ESPECIE", "ESPECIFICAR", "ESPECTACULO", "ESPECTADOR", "ESPECTRO", "ESPECULAR", "ESPEJO", "ESPERA", "ESPERANZA",
    "ESPERAR", "ESPESO", "ESPESOR", "ESPIA", "ESPIAR", "ESPIGA", "ESPINA", "ESPINAZO", "ESPINILLA", "ESPINO",
    "ESPINOSO", "ESPIRAL", "ESPIRAR", "ESPIRITU", "ESPIRITUAL", "ESPLENDIDO", "ESPLENDOR", "ESPOLEAR", "ESPOLON", "ESPONJA",
    "ESPONTANEO", "ESPOSA", "ESPOSO", "ESPUELA", "ESPUMA", "ESQUELA", "ESQUELETO", "ESQUEMA", "ESQUI", "ESQUINA",
    
    # Palabras comunes F-G
    "FABRICA", "FABRICAR", "FABULA", "FACIL", "FACILITAR", "FACTOR", "FACTURA", "FACULTAD", "FAENA", "FAJA",
    "FALDA", "FALLO", "FALSO", "FALTA", "FALTAR", "FAMA", "FAMILIA", "FAMILIAR", "FAMOSO", "FAROL",
    "FASE", "FASTIDIAR", "FATAL", "FATIGA", "FATIGAR", "FAVOR", "FAVORABLE", "FAVORECER", "FEBRERO", "FECHA",
    "FELICIDAD", "FELICITAR", "FELIZ", "FEMENINO", "FENOMENO", "FEO", "FERIA", "FEROZ", "FERROCARRIL", "FERTIL",
    "FERVOR", "FESTEJAR", "FESTEJO", "FESTIVAL", "FIAR", "FIBRA", "FICCION", "FICHA", "FIDELIDAD", "FIEBRE",
    "FIEL", "FIERA", "FIESTA", "FIGURA", "FIGURAR", "FIJAR", "FIJO", "FILA", "FILETE", "FILMAR",
    "FILO", "FILOSOFIA", "FILTRAR", "FILTRO", "FINAL", "FINALIZAR", "FINANCIERO", "FINCA", "FINGIR", "FINO",
    "FIRMA", "FIRMAR", "FIRME", "FIRMEZA", "FISCAL", "FISICA", "FISICO", "FLACO", "FLECHA", "FLEXIBLE",
    "FLOJO", "FLOR", "FLORECER", "FLORERO", "FLORISTA", "FLOTA", "FLOTAR", "FLUIR", "FLUJO", "FOCO",
    "FOGON", "FOLLETO", "FOMENTAR", "FONDA", "FONDO", "FORMA", "FORMAL", "FORMAR", "FORMIDABLE", "FORMULA",
    "FORO", "FORRAR", "FORRO", "FORTALECER", "FORTALEZA", "FORTUNA", "FORZAR", "FORZOSO", "FOSA", "FOSFORO",
    "FOTO", "FOTOGRAFIA", "FOTOGRAFO", "FRACASAR", "FRACASO", "FRACCION", "FRACTURA", "FRAGANCIA", "FRAGANTE", "FRAGIL",
    "FRAGMENTO", "FRAGUA", "FRAILE", "FRAMBUESA", "FRANCES", "FRANCIA", "FRANCO", "FRANQUEAR", "FRANQUEZA", "FRANQUICIA",
    "FRASE", "FRATERNAL", "FRATERNIDAD", "FRAUDE", "FRAZADA", "FRECUENCIA", "FRECUENTE", "FRECUENTAR", "FREGADERO", "FREGAR",
    "FREIR", "FRENAR", "FRENO", "FRENTE", "FRESA", "FRESCO", "FRESCURA", "FRESNO", "FRIALDAD", "FRICCION",
    "FRIGORIFICO", "FRIJOL", "FRIO", "FRIOLENTO", "FRIOLERA", "FRISO", "FRITO", "FRITURA", "FRIVOLIDAD", "FRIVOLO",
    "FRONTERA", "FRONTERIZO", "FRONTIS", "FRONTON", "FROTAR", "FRUCTIFERO", "FRUGAL", "FRUICION", "FRUNCIR", "FRUSLERIA",
    "FRUSTRACION", "FRUSTRAR", "FRUTA", "FRUTAL", "FRUTERIA", "FRUTERO", "FRUTO", "FUEGO", "FUELLE", "FUENTE",
    "FUERA", "FUERTE", "FUERZA", "FUGA", "FUGARSE", "FUGAZ", "FUGITIVO", "FULANO", "FULGOR", "FULMINANTE",
    "FULMINAR", "FUMADOR", "FUMAR", "FUNCION", "FUNCIONAR", "FUNCIONARIO", "FUNDA", "FUNDACION", "FUNDADOR", "FUNDAMENTAL",
    
    # Palabras comunes G-H
    "GAFAS", "GALAN", "GALERIA", "GALLETA", "GALLINA", "GALLO", "GALOPAR", "GALOPE", "GANAR", "GANADO",
    "GANANCIA", "GANCHO", "GARAJE", "GARANTIA", "GARANTIZAR", "GARGANTA", "GARITA", "GARRA", "GASTAR", "GASTO",
    "GATO", "GAVILAN", "GAVIOTA", "GEMELO", "GEMIR", "GENERAL", "GENERAR", "GENERO", "GENEROSO", "GENIAL",
    "GENIO", "GENTE", "GENUINO", "GEOGRAFIA", "GEOMETRIA", "GERENTE", "GERMEN", "GESTO", "GIGANTE", "GIRAR",
    "GIRO", "GITANO", "GLACIAL", "GLOBAL", "GLOBO", "GLORIA", "GLORIOSO", "GLOTON", "GOBERNADOR", "GOBERNAR",
    "GOBIERNO", "GOLFO", "GOLONDRINA", "GOLOSINA", "GOLPE", "GOLPEAR", "GOMA", "GORDO", "GORILA", "GORRA",
    "GORRION", "GOTA", "GOTEAR", "GOZAR", "GOZO", "GRABAR", "GRACIA", "GRACIOSO", "GRADO", "GRADUAL",
    "GRAFICO", "GRAMA", "GRAMATICA", "GRANDE", "GRANDEZA", "GRANERO", "GRANITO", "GRANIZO", "GRANJA", "GRANO",
    "GRASA", "GRATIS", "GRATITUD", "GRATO", "GRAVE", "GRAVEDAD", "GRIEGO", "GRIETA", "GRILLO", "GRIPE",
    "GRIS", "GRITAR", "GRITO", "GROSERO", "GRUESO", "GRUMO", "GRUPO", "GUANTE", "GUAPO", "GUARDAR",
    "GUARDIA", "GUARDIAN", "GUARIDA", "GUARNICION", "GUERRA", "GUERRERO", "GUIA", "GUIAR", "GUIJARRO", "GUINDA",
    "GUINDAR", "GUINO", "GUION", "GUIRNALDA", "GUISA", "GUISADO", "GUISANTE", "GUISAR", "GUISO", "GUITARRA",
    "GULA", "GUSANO", "GUSTAR", "GUSTO", "GUSTOSO", "HABER", "HABIL", "HABILIDAD", "HABITACION", "HABITANTE",
    "HABITAR", "HABITO", "HABITUAL", "HABLAR", "HACER", "HACHA", "HACIA", "HACIENDA", "HADA", "HALAGAR",
    "HALAGO", "HALLAR", "HAMACA", "HAMBRE", "HAMBRIENTO", "HARINA", "HARTAR", "HARTO", "HASTA", "HAZANA",
    "HEBRA", "HECHIZO", "HECHO", "HELADA", "HELADO", "HELAR", "HEMBRA", "HEREDAD", "HEREDAR", "HEREDERO",
    "HERENCIA", "HERIDA", "HERIR", "HERMANA", "HERMANO", "HERMOSO", "HERMOSURA", "HEROE", "HEROICO", "HERRADURA",
    "HERRAMIENTA", "HERRERO", "HERVIR", "HIELO", "HIERBA", "HIERRO", "HIGADO", "HIGIENE", "HIJO", "HILAR",
    "HILO", "HIMNO", "HINCHAR", "HIPOTECA", "HISTORIA", "HISTORICO", "HOGAR", "HOGUERA", "HOJA", "HOJEAR",
    "HOLA", "HOLGAR", "HOMBRE", "HOMBRO", "HOMENAJE", "HONDO", "HONESTO", "HONGO", "HONOR", "HONRA"
]

def insertar_palabras():
    """Inserta las palabras en la base de datos"""
    # Conectar a la base de datos usando las variables de entorno
    connection = pymysql.connect(
        host=os.getenv('MYSQL_DATABASE_HOST', 'localhost'),
        user=os.getenv('MYSQL_DATABASE_USER', 'root'),
        password=os.getenv('MYSQL_DATABASE_PASSWORD', 'admin'),
        database=os.getenv('MYSQL_DATABASE_DB', 'wordbomb'),
        charset='utf8mb4',
        cursorclass=pymysql.cursors.DictCursor
    )
    
    try:
        with connection.cursor() as cursor:
            # Contador de palabras insertadas
            insertadas = 0
            duplicadas = 0
            
            for palabra in palabras:
                try:
                    # Intentar insertar la palabra
                    query = "INSERT INTO PALABRA (Palabra) VALUES (%s)"
                    cursor.execute(query, (palabra,))
                    insertadas += 1
                    print(f"✓ Insertada: {palabra}")
                except Exception as e:
                    # Si la palabra ya existe, continuar
                    if "Duplicate entry" in str(e):
                        duplicadas += 1
                        print(f"⊘ Ya existe: {palabra}")
                    else:
                        print(f"✗ Error al insertar {palabra}: {e}")
            
            # Confirmar los cambios
            connection.commit()
            
            print("\n" + "="*50)
            print(f"Proceso completado:")
            print(f"  - Palabras insertadas: {insertadas}")
            print(f"  - Palabras duplicadas: {duplicadas}")
            print(f"  - Total procesadas: {len(palabras)}")
            print("="*50)
            
    except Exception as e:
        print(f"Error general: {e}")
        connection.rollback()
    finally:
        connection.close()

if __name__ == "__main__":
    print("Iniciando inserción de palabras...")
    print("="*50)
    insertar_palabras()
